# Website Configuration

# Site Information
site_name: ANDREAS LEKANG ®
site_description: Photography portfolio of Andreas Lekang in Oslo
site_author: Andreas Lekang

# SEO Settings
seo:
  title: Andreas Lekangs fotografi portfolio
  description: Photography portfolio of Andreas Lekang in Oslo
  keywords: photography, portfolio, Andreas Lekang, Oslo

# Navigation Menu
menu:
  - label: Bilder
    url: # Add your URL for the "Bilder" section here
  - label: Om meg
    url: # Add your URL for the "Om meg" section here
  - label: Kontakt
    url: # Add your URL for the "Kontakt" section here

# Social Media Links
social_media:
  - platform: LinkedIn
    url: https://no.linkedin.com/in/andreas-lekang-a73377131
  - platform: Instagram
    url: https://www.instagram.com/andreaslekang/
  - platform: Facebook
    url: https://www.facebook.com/profile.php?id=100000740613256

# Contact Information
contact:
  email: andreas.lekang@gmail.com
  phone: +4794196040

# Footer Text
footer_text: Laget av Marcus Evensen ® 2023

# Google Analytics Tracking ID (if applicable)
google_analytics_tracking_id: G-L6S931DKV0

# Other Configuration Options
# Add any other configuration options or settings specific to your website here.
